### PR TITLE
Update to Auth 2.0

### PR DESCRIPTION
**Pull request by HaoK**
Demonstrate what this sample would look like on the new Auth 2.0 stack

### CODE REVIEW

**Comment by Eilon** [comment]
@HaoK does this PR also need to include deleting this file: `~TodoListWebApp/App_Start/Startup.Auth.cs` ?

**Comment by HaoK** [comment]
Ah yeah, I inlined that code

**Comment by HaoK** [comment]
I used the edit button to create a PR for the first time :)

**Comment by Eilon** [comment]
That's how I do it 😄 But would be good to update the PR so we can share with interested parties.

**Comment by HaoK** [comment]
Couldn't figure out how to fix this via website, created a new one in the fork https://github.com/Azure-Samples/active-directory-webapp-webapi-multitenant-openidconnect-aspnetcore/pull/4

**Pull request closed without merging**
